version: "3.3"

services:
  sentiment-database:
    image: mongo
    container_name: sentiment-database
    ports:
      - "27017:27017" # app port
    volumes:
      - database-data:/data/db
    networks:
      sentiment-network:
        aliases:
          - "sentiment-database"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" # app port
      - "15672:15672" # management port
    networks:
      sentiment-network:
        aliases:
          - "rabbitmq"

  sentiment-web:
    image: sentiment-web
    container_name: sentiment-web
    build: ./sentiment-web
    ports:
      - 9100:80
    depends_on:
      - sentiment-service
    networks:
      sentiment-network:
        aliases:
          - "sentiment-web"

  sentiment-service:
    image: sentiment-service
    container_name: sentiment-service
    build: ./sentiment-service
    ports:
      - 9200:9200
    environment:
      - repository.host=sentiment-database
      - repository.port=27017
      - rabbitmq.host=rabbitmq
      - rabbitmq.port=5672
    depends_on:
      - sentiment-database
      - rabbitmq
    networks:
      sentiment-network:
        aliases:
          - "sentiment-service"

  sentiment-engine:
    image: sentiment-engine
    container_name: sentiment-engine
    build: ./sentiment-engine
    ports:
      - 9300:9300
    environment:
      - repository.host=sentiment-database
      - repository.port=27017
      - rabbitmq.host=rabbitmq
      - rabbitmq.port=5672
    depends_on:
      - sentiment-database
      - rabbitmq
      - sentiment-service
    networks:
      sentiment-network:
        aliases:
          - "sentiment-engine"

networks:
  sentiment-network:
    driver: bridge

volumes:
  database-data:

#    environment:
#      - DATABASE_URI=mongodb://sampledb/sample